### ISSUE TITLE
@get /tapahtuma/{id}/myyntitapahtumat

### ISSUE THREAD

**Issue by bfm471** [vilp91/Lipunmyyntijarjestelma#94]

**Comment by bfm471** [comment]
Palauttaa pyydettyyn tapahtumaan liittyvät myyntitapahtumat
Kuvittelen, että tämä tarjoaa tarvittavat tiedot Myyntiraporttia varten..

**Comment by Romaalie** [comment]
Sain tämän kyllä toimimaan, mutta tätä tutkiessa tuli vastaan sellainen ongelma, että ilmeisesti meidän nimeämiskäytännöt eli "_" käyttö joissain meidän entityissä on vähän huono juttu. Tuota alaviivaa käytetään Spring Bootin tietokantahauissa erityistapauksissa kuten tässä dokumentaatiossa mainitaan: 

"Because we treat the underscore character as a reserved character, we strongly advise following standard Java naming conventions (that is, not using underscores in property names but using camel case instead)."

Lähde:
https://docs.spring.io/spring-data/jpa/reference/repositories/query-methods-details.html#repositories.query-methods.query-property-expressions

Laitan tänne vielä muistiin sen itse metodin, jonka pitäisi toimia kun/jos ongelmalliset "_" käyttävät entityjen attribuutit nimetään uudelleen camel casella:

    @GetMapping("/tapahtumat/{id}/myyntitapahtumat")
    public ResponseEntity<?> getTapahtumanMyyntitapahtumat(@PathVariable Long id) {

        // tarkistetaan löytyykö annetulla id:llä tapahtuma ja palautetaan virhe viesti jos ei löydy
        if (!tapahtumaRepository.existsById(id)) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Tapahtumaa ei löydy tällä id:llä");
        }

        List<Tapahtuma> tapahtumat = tapahtumaRepository.findByTapahtumaId(id);

        List<TapahtumanLipputyyppi> tapahtumanLipputyypit = tapahtumanLipputyyppiRepository.findByTapahtumaIn(tapahtumat);

        List<Lippu> liput = lippuRepository.findByTapahtumanLipputyyppiIn(tapahtumanLipputyypit);

        List<Myyntitapahtuma> myyntitapahtumat = myyntitapahtumaRepository.findByLiputIn(liput);

        return ResponseEntity.ok().body(myyntitapahtumat);
    }

**Comment by bfm471** [comment]
Mä ainakin näkisin, että tämä olisi tärkeä osa kokonaisuutta. Eli jos sulla @Romaalie on jo tehtynä, niin laita ihmeessä julki ja toimintaan :)
